main:
    resource: "@MainBundle/Controller/"
    type:     annotation

document.search:
    resource: '@RestBundle/Controller/SearchController.php'
    type:     annotation
    prefix:   /document

document.index:
    resource: '@RestBundle/Controller/IndexController.php'
    type:     annotation
    prefix:   /document

document.create:
    resource: '@RestBundle/Controller/CreateController.php'
    type:     annotation
    prefix:   /document

document.delete:
    resource: '@RestBundle/Controller/DeleteController.php'
    type:     annotation
    prefix:   /document

document.update:
    resource: '@RestBundle/Controller/UpdateController.php'
    type:     annotation
    prefix:   /document

document.file:
    resource: "@FileBundle/Controller"
    type:     annotation
    prefix:   /document

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
