services:

  ####### Domain interface services wiring #######
  document.repository:
    class: Document\Domain\DocumentRepository
    alias: document.repository.mongo

  document.filestorage:
    class: Document\Domain\DocumentFileStorage
    alias: document.filestorage.flysystem


  ####### Implemented services wiring #######
  document.repository.mongo:
    class: Document\Bridge\MongoDB\DocumentRepository
    arguments:
      - "@mongo.database"
      - "@document.filestorage"

  document.filestorage.flysystem:
    class: Document\Bridge\FlySystem\DocumentFileStorage
    arguments:
      - "@flysystem.client.local"


  ####### Client factories #######
  mongo.database:
    class: MongoDB\Database
    factory: [Document\Bridge\MongoDB\MongoDatabaseFactory, getClient]
    arguments:
      - "%database_name%"

  flysystem.client.local:
    class: League\Flysystem\Filesystem
    factory: [Document\Bridge\FlySystem\FlySystemClientFactory, getLocalClient]
    arguments:
      - "%storage_root%"

  ####### Param Converters #######
  converter.document.id:
    class: Document\RestBundle\ParamConverter\DocumentParamConverter
    arguments:
      - "@document.repository"
    tags:
      - { name: request.param_converter}
