- name: add php ppa
  apt_repository: repo='ppa:ondrej/php' state=present

- name: install php requirements for Gerald
  apt: name=php{{ php.version }}-{{ item }} state=present
  with_items:
    - json
    - curl
    - xml
    - mbstring
    - intl
    - opcache
    - mongodb
    - xdebug
    - apcu
    - pdo
    - zip

- name: install php{{ php.version }}-fpm
  apt: name=php{{ php.version }}-fpm state=present

- name: Set higher max upload for FPM
  lineinfile:
    dest: /etc/php/{{ php.version }}/fpm/php.ini
    regexp: "upload_max_filesize = "
    line: "upload_max_filesize = 50M"

- name: Set higher max post body for FPM
  lineinfile:
    dest: /etc/php/{{ php.version }}/fpm/php.ini
    regexp: "post_max_size = "
    line: "post_max_size = 50M"

- name: restart php-fpm
  service: name=php{{ php.version }}-fpm state=restarted
