- name: Add Mongo packages repo
  apt_key: id=0C49F3730359A14518585931BC711F9BA15703C6  keyserver=keyserver.ubuntu.com
- name: add repo itself
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse' state=present
- name: install packages
  apt: pkg=mongodb-org state=present

- name: Start mongod
  service: name=mongod state=started
