---
- name: generate the server locale
  locale_gen: name={{ locale }} state=present

- name: set locale
  lineinfile: dest=/etc/default/locale regexp='^LANG=' line='LANG={{ locale }}'

- name: set timezone to Europe/Amsterdam
  timezone:
    name: Europe/Amsterdam
